model_name_or_path: Qwen/Qwen3-4B-Base
model_revision: main
use_flash_attn: true
tokenizer_name: Qwen/Qwen3-4B-Base
use_slow_tokenizer: false
dataset_mixer:
  /home/epsteine/post-training/datasets/tulu3_sft_year2007.jsonl: "1.0"
dataset_mixer_list: null
dataset_name: null
dataset_config_name: null
max_seq_length: 4096
preprocessing_num_workers: 128
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 1.0e-04
lr_scheduler_type: cosine
warmup_ratio: 0.03
weight_decay: 0.0
num_train_epochs: 2
output_dir: output/qwen3_year2007_full
with_tracking: false
report_to: []
logging_steps: 10
seed: 17
gradient_checkpointing: true
dataset_mix_dir: output/qwen3_year2007_full
checkpointing_steps: 500
keep_last_n_checkpoints: 3
